### ISSUE TITLE
请问一下就是这个项目，没有附带数据库么，数据库需要自己去设计么？

### ISSUE THREAD

**Issue by HaipaNote** [IChooseBearPaws/music-player#3]

**Comment by Sugar0612** [comment]
不，这个项目数据库用的是 阿里云的数据库，不过目前我已经没有续费阿里云数据库了，所以说可能需要你在本地自己去设计数据库以及相应的字段了，不过比较麻烦，你也可以看看这个仓库的另一个分支：KtvPlayer, 里面的数据库相对来说容易一些，我也可以提供给你他相应的数据库字段（如果你需要的话。。。 这是我的qq：287276293.
